import { Download } from 'lucide-react'
import type {ScanMeta} from "@/types/types"
type ReportResult = {
    prediction?: string;
    confidence?: number;
    riskLevel?: string;
    reasons?: string[];
    extractedText?: string;
    urls?: string[];
};

type ReportButtonProps = {
    result: ReportResult;
    scanMeta: ScanMeta;
};
export default function ReportButton({ result, scanMeta } : ReportButtonProps) {
    function generateReport() {
        const { prediction, confidence, riskLevel, reasons = [], extractedText, urls = [] } = result
        const { type, input, timestamp } = scanMeta

        const lines = [
            '════════════════════════════════════════════════════',
            '         PHISHGUARD AI – SCAN REPORT',
            '════════════════════════════════════════════════════',
            '',
            `Timestamp   : ${new Date(timestamp).toLocaleString()}`,
            `Input Type  : ${type}`,
            `Prediction  : ${prediction?.toUpperCase()}`,
            `Confidence  : ${Math.round((confidence || 0) * 100)}%`,
            `Risk Level  : ${riskLevel}`,
            '',
            '── Detection Indicators ──────────────────────────',
            reasons.length ? reasons.map(r => `  • ${r}`).join('\n') : '  None detected',
            '',
        ]

        if (urls.length) {
            lines.push('── Detected URLs ─────────────────────────────────')
            urls.forEach(u => lines.push(`  ⚠ ${u}`))
            lines.push('')
        }

        if (extractedText) {
            lines.push('── OCR Extracted Text ────────────────────────────')
            lines.push(extractedText)
            lines.push('')
        }

        if (input && type === 'text') {
            lines.push('── Scanned Content ───────────────────────────────')
            lines.push(input.slice(0, 500) + (input.length > 500 ? '...' : ''))
            lines.push('')
        }

        lines.push('════════════════════════════════════════════════════')
        lines.push('Generated by PhishGuard AI · For educational use only')

        const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `phishguard-report-${Date.now()}.txt`
        a.click()
        URL.revokeObjectURL(url)
    }

    return (
        <button onClick={generateReport} className="button-secondary text-sm py-2 px-3 gap-1.5" aria-label="Download scan report">
            <Download size={14} aria-hidden />
            Export Report
        </button>
    )
}
